name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - '**'        # matches any branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # or your preferred Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: |
        cd packages/core
        npm test -- --coverage